### ISSUE TITLE
La barre de recherche des clients inactifs ne fonctionne pas [Fonctionnel/Mineur]

### ISSUE THREAD

**Issue by Antoine-BL** [SamuelMenard/PetitesPuces#6]
### Description
La barre de recherche cache toutes les demandes.

Ceci peut-être parce que la recherche ne marche pas, ou parce que la recherche se base sur un critère qui n'est pas visible (genre, le nom plutôt que le courriel)

### Étapes pour reproduire:
1. Naviguer vers la page en tant qu'admin
2. Tapper quelque chose dans la barre de recherche
3. Toutes les demandes disparaissent

**Comment by SamuelMenard** [comment]
Fix, merci!
