### ISSUE TITLE
Problèmes de suppression de compte avec commandes [Fonctionnel, majeur]

### ISSUE THREAD

**Issue by Antoine-BL** [SamuelMenard/PetitesPuces#7]
### Description
Lorsqu'on désactive un compte client dans la section admin, il disparaît de la liste mais n'est pas supprimé de la BD.

### À vérifier
Si, quand un client sans commande est supprimé, ses paniers son supprimés.

**Comment by SamuelMenard** [comment]
J,ai testé et tout semble fonctionnel... Pas capable de recréer le bug.

**Comment by Antoine-BL** [comment]
Ça marche
